version: 2
project_name: ima
builds:
  - main: ./main.go
    binary: ima
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: tar.gz
release:
  github:
    owner: tanjeetsarkar
    name: ima