name: ima Release

on:
  push:
    tags:
      - 'v*.*.*'  # Matches semantic version tags like v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # (Optional) Run tests to ensure your application builds and passes all checks
      - name: Run tests
        run: go test ./...

      # Use GoReleaser to build and publish the release artifacts
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
